// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xookobxjvigkejqmqehw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvb2tvYnhqdmlna2VqcW1xZWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODI0MjEsImV4cCI6MjA2OTk1ODQyMX0.zZNh4Ifp5-d3Dx89gAki1SJ-iKqHdzjfVe5FkipgogQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});